In [1]:
from sklearn.datasets import make_classification
import torch 

In [3]:
X, y = make_classification(
    n_samples = 10, # Number of samples
    n_features = 2, # Number of features
    n_informative = 2, # Number of informative features
    n_redundant = 0, # Number of redundant features
    n_classes = 2, # Number of classes
    random_state = 42 # For reproducibility
) 

In [6]:
X.shape

(10, 2)

In [7]:
# Convert data into PyTorch Tensors
X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.long)

In [8]:
from torch.utils.data import Dataset, DataLoader

In [10]:
class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]


dataset = CustomDataset(X, y)

In [11]:
len(dataset)

10

In [13]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

In [14]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [20]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("=" * 80)

tensor([[ 1.7273, -1.1858],
        [-0.9382, -0.5430]])
tensor([1, 1])
tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
tensor([[-0.7206, -0.9606],
        [ 1.7774,  1.5116]])
tensor([0, 1])
tensor([[ 1.8997,  0.8344],
        [-1.9629, -0.9923]])
tensor([1, 0])
tensor([[-2.8954,  1.9769],
        [-0.5872, -1.9717]])
tensor([0, 0])
