In [27]:
import torch
print(torch.__version__)

2.13.0+cpu


In [28]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [29]:
torch.zeros(6, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [30]:
torch.ones(6, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [31]:
torch.rand(6, 5)

tensor([[0.0665, 0.0198, 0.2469, 0.2746, 0.5370],
        [0.5286, 0.3013, 0.3963, 0.7990, 0.3306],
        [0.1010, 0.9692, 0.5185, 0.7258, 0.9107],
        [0.3398, 0.6710, 0.0039, 0.5416, 0.2202],
        [0.1901, 0.1470, 0.2308, 0.0855, 0.2691],
        [0.1288, 0.9418, 0.0940, 0.8407, 0.1574]])

In [32]:
x.shape

torch.Size([3, 3])

In [33]:
i = torch.rand(6, 5)
i

tensor([[0.1425, 0.6908, 0.6216, 0.6471, 0.9389],
        [0.6755, 0.0336, 0.2973, 0.5400, 0.3919],
        [0.6901, 0.6389, 0.0953, 0.6496, 0.6150],
        [0.9831, 0.3509, 0.0840, 0.1506, 0.2836],
        [0.7969, 0.1218, 0.2710, 0.9034, 0.2144],
        [0.3396, 0.6224, 0.2623, 0.5476, 0.6969]])

In [34]:
print(i[3, 2])

tensor(0.0840)


In [35]:
s = torch.rand(6, 5)
a = torch.rand(6, 5)
print(s)
print(a)

tensor([[0.5623, 0.1023, 0.4475, 0.1464, 0.7345],
        [0.5079, 0.2150, 0.5319, 0.0731, 0.7952],
        [0.9847, 0.7463, 0.4575, 0.6588, 0.1391],
        [0.6636, 0.9637, 0.0991, 0.7818, 0.5144],
        [0.0707, 0.6254, 0.7851, 0.8853, 0.3178],
        [0.0840, 0.7366, 0.4276, 0.4781, 0.6939]])
tensor([[0.4663, 0.4281, 0.7833, 0.1383, 0.1167],
        [0.2587, 0.0915, 0.5945, 0.9765, 0.3100],
        [0.6762, 0.6448, 0.4511, 0.3247, 0.9379],
        [0.1240, 0.2712, 0.7725, 0.3462, 0.5019],
        [0.9473, 0.7685, 0.2006, 0.4147, 0.0946],
        [0.4840, 0.3930, 0.5802, 0.7989, 0.7728]])


In [36]:
print(s + a)
print(s - a)
print(s * a)
print(s / a)

tensor([[1.0286, 0.5304, 1.2308, 0.2847, 0.8512],
        [0.7666, 0.3066, 1.1264, 1.0495, 1.1053],
        [1.6609, 1.3910, 0.9086, 0.9835, 1.0770],
        [0.7876, 1.2348, 0.8716, 1.1279, 1.0163],
        [1.0180, 1.3939, 0.9857, 1.3000, 0.4124],
        [0.5680, 1.1296, 1.0078, 1.2770, 1.4667]])
tensor([[ 0.0961, -0.3258, -0.3358,  0.0080,  0.6179],
        [ 0.2492,  0.1235, -0.0625, -0.9034,  0.4852],
        [ 0.3084,  0.1015,  0.0064,  0.3341, -0.7988],
        [ 0.5396,  0.6925, -0.6733,  0.4356,  0.0124],
        [-0.8767, -0.1432,  0.5844,  0.4706,  0.2232],
        [-0.4000,  0.3436, -0.1526, -0.3208, -0.0789]])
tensor([[0.2622, 0.0438, 0.3505, 0.0202, 0.0857],
        [0.1314, 0.0197, 0.3162, 0.0713, 0.2466],
        [0.6659, 0.4812, 0.2064, 0.2139, 0.1305],
        [0.0823, 0.2613, 0.0766, 0.2706, 0.2582],
        [0.0670, 0.4806, 0.1575, 0.3672, 0.0301],
        [0.0407, 0.2895, 0.2481, 0.3820, 0.5363]])
tensor([[1.2061, 0.2390, 0.5713, 1.0581, 6.2961],
        [1.9631, 

In [37]:
# Points out to same memory 
import numpy as np
arr = np.array([25, 35, 45])
n = torch.from_numpy(arr)
print(n)

tensor([25, 35, 45])


In [38]:
import torch
x = torch.tensor([1., 2., 3., 4.])
y = torch.tensor([2., 4., 6., 8.])

w = torch.tensor(0.0)
b = torch.tensor(0.0)

y_pred = w * x + b

loss = torch.mean((y_pred - y) ** 2)

print("Actual values:", y)
print("Predicted values:", y_pred)
print("Loss:", loss)

Actual values: tensor([2., 4., 6., 8.])
Predicted values: tensor([0., 0., 0., 0.])
Loss: tensor(30.)
